/*
 * This file is a part of VideoLibrary Interface
 * Copyright © Vyacheslav Krylov (slavone@protonmail.ch) 2021
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package me.vkryl.videolib;

import android.content.Context;
import android.net.Uri;

/**
 * Configuration suggestion generated by the library.
 *
 * On the client side, this will be used when displaying a slider.
 */
public class CompressionConfigurationSuggestion {
  /**
   * Unique name of the suggestion within a suggestion list.
   *
   * Can be the same as {@link #displayName} (but not limited to its value).
   * Example: "1080p60fps", "720p", "360p", etc
   */
  public String id;

  /**
   * Identifier of the suggestion group.
   *
   * Suggestions with the same <code>groupId</code> will be combined on the UI level.
   *
   * Example: if library uses "1080p60fp" and "1080p" in the {@link #id},
   * <code>groupId</code> could be equal to "1080p" for both of the suggestions.
   *
   * Note that these example values are just a suggestion,
   * and you are free to use whatever values you find more reasonable.
   */
  public String groupId;

  /**
   * Display name of the suggestion that could be shown to the end user.
   *
   * Example: "1080p60fps", "720p", etc.
   */
  public String displayName;

  /**
   * Estimated output size for the suggested configuration.
   */
  public EstimatedOutputSize estimatedSize;

  /**
   * Suggested configuration to pass to the {@link VideoLibrary#convertVideo(Context, Uri, OutputVideoConfiguration, OverlayProvider, String, ConversionCallback)}
   */
  public CompressionConfiguration configuration;
}
